name: drm
# description: ""
description: "Decentrazed Rent Market is an innovative cryptocurrency exchange platform, specializing in providing investors with access to shares of rental funds."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  aptos: ^0.0.5
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  de_log: ^1.0.0
  sentry: ^7.14.0
  sentry_flutter: ^7.14.0
  bloc_concurrency: ^0.2.3
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

