name: drm
description: '''"Decentrazed Rent Market" is an innovative cryptocurrency exchange platform, 
specializing in providing investors with access to shares of rental funds. 
Our platform uses blockchain technology to ensure security, transparency,
and decentralization, 
allowing participants to make transactions without the need for intermediaries.'''

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
